title: ROllerozxa
description: "ROllerozxa's Blog"
url: https://voxelmanip.se

baseurl: /

exclude:
  - CNAME
  - build_production.sh
  - _site_production/
  - patches/

permalink: pretty
paginate: 10
paginate_path: /page/:num/

sass:
  style: compressed
  sourcemap: never

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    hellip: "..."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate
