title: ROllerozxa
description: "ROllerozxa's Blog"
url: https://voxelmanip.se

baseurl: /

exclude:
  - CNAME

permalink: pretty
paginate: 10
paginate_path: /page/:num/

sass:
  style: compressed
  sourcemap: never

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate
