title: ROllerozxa
description: "ROllerozxa's Blog"
url: https://voxelmanip.se

baseurl: /

lang: en_GB

exclude:
  - CNAME
  - build_production.sh
  - _site_production/
  - patches/

permalink: pretty
paginate: 10
paginate_path: /page/:num/

sass:
  style: compressed
  sourcemap: never

kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  typographic_symbols:
    hellip: "..."

collections:
  projects:
    output: true
    layout: project
    sort_by: timeframe

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
